# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSEi2je1UO3AFtL0R1TqPBmQMZz78nDE
"""

import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

def kmeans_clustering(latent_vectors, n_clusters=2):
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    labels = kmeans.fit_predict(latent_vectors)
    silhouette_avg = silhouette_score(latent_vectors, labels)
    return labels, silhouette_avg